AWSTemplateFormatVersion: "2010-09-09"
Description: "Create Client-Server"
    
# ------------------------------------------------------------
#  Metadate
# ------------------------------------------------------------
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Parameters: 
          - PJPrefix
          - EC2AMI
          - InstanceType
          - KeyName
          - UserName

# ------------------------------------------------------------
# Input Parameters
# ------------------------------------------------------------
Parameters:
### Project Prefix ###
  PJPrefix:
    Type: 'String'
    Default: "cfn-ec2-client"
  EC2AMI:
    Type: 'String'
    Default: "ami-0bba69335379e17f8"
  InstanceType:
    Type: 'String'
    Default: "t2.micro"
  KeyName:
    Type: 'AWS::EC2::KeyPair::KeyName'
    Default: "inamura"
  UserName:
    Type: 'String'
    Default: "inamura"
    
### Resources ###
Resources:
# ------------------------------------------------------------
# EC2
# ------------------------------------------------------------
### ClientServer ###
  ClientServer:
    Type: AWS::EC2::Instance
    Properties: 
      ImageId: !Ref EC2AMI
      InstanceType: !Ref InstanceType 
      KeyName: !Ref KeyName
      NetworkInterfaces: 
        - NetworkInterfaceId: !Ref ENI 
        # - AssociatePublicIpAddress: "false"
          DeviceIndex: "0"
        #   SubnetId: !ImportValue cfn-network-B-private-subnet
        #   GroupSet:
        #     - !Ref ClientSG
      Tags:
        - Key: Name
          Value: !Sub "${PJPrefix}-ClientServer-inamura"
        - Key: UserName
          Value: !Ref UserName 

### BassionServer ###
  BassionServer:
    Type: AWS::EC2::Instance
    Properties: 
      ImageId: !Ref EC2AMI
      InstanceType: !Ref InstanceType 
      KeyName: !Ref KeyName
      NetworkInterfaces: 
        - AssociatePublicIpAddress: "true"
          DeviceIndex: "0"
          SubnetId: !ImportValue cfn-network-B-public-subnet
          GroupSet:
            - !Ref ClientSG
      Tags:
        - Key: Name
          Value: !Sub "${PJPrefix}-BassionServer-inamura"
        - Key: UserName
          Value: !Ref UserName 
# ------------------------------------------------------------
# ENI
# ------------------------------------------------------------
  ENI: 
    Type: AWS::EC2::NetworkInterface 
    Properties: 
      Tags: 
      - Key: UserName 
        Value: !Ref UserName
      SourceDestCheck: 'false' 
      GroupSet: 
      - !Ref ClientSG
      SubnetId: !ImportValue cfn-network-B-private-subnet
      PrivateIpAddress: 192.168.10.10


# ------------------------------------------------------------
# SecurityGroup
# ------------------------------------------------------------
### WebServer Security Group ###
  ClientSG:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: "ClientServer SG"
      GroupName: !Sub "${PJPrefix}-Client-SG-inamura"
      VpcId: !ImportValue cfn-network-B-vpc
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort : 22
          ToPort : 22
          CidrIp: 0.0.0.0/0
      Tags: 
        - Key: Name
          Value: !Sub "${PJPrefix}-Client-SG"
        - Key: UserName
          Value: !Ref UserName 

  EndpointSG:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: "Endpoint SG"
      GroupName: !Sub "${PJPrefix}-Endpoint-SG-inamura"
      VpcId: !ImportValue cfn-network-B-vpc
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort : 80
          ToPort : 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort : 22
          ToPort : 22
          CidrIp: 0.0.0.0/0
      Tags: 
        - Key: Name
          Value: !Sub "${PJPrefix}-Endpoint-SG"
        - Key: UserName
          Value: !Ref UserName 

# ------------------------------------------------------------
# EndPoint
# ------------------------------------------------------------
  VpcEndpoint:
    Type: "AWS::EC2::VPCEndpoint"
    Properties:
      VpcId: !ImportValue cfn-network-B-vpc
      ServiceName: !ImportValue cfn-ec2-web-VPCEndpoint
      VpcEndpointType: Interface
      PrivateDnsEnabled: true
      SubnetIds: 
        - !ImportValue cfn-network-B-private-subnet
      SecurityGroupIds:
        - !Ref EndpointSG

# ------------------------------------------------------------
# Output Parameters
# ------------------------------------------------------------
Outputs:
  VPCEndpointDNS:
    Value: !Join
      - ',' 
      - !GetAtt VpcEndpoint.DnsEntries
    Export:
      Name: !Sub "${PJPrefix}-EndpointDNS"